### ISSUE TITLE
Regularjs是如何获取焦点事件的呢？

### ISSUE THREAD

**Issue by YouTuQiong** [regularjs/guide#11]
我在官方文档找了很久都没有找到

**Comment by fengzilong** [comment]
```html
<input on-focus="..." />
```

**Comment by leeluolee** [comment]
其实文档是有写，  regularjs和ng不一样，所有事件都是被预先处理的，  都是on-xx  
![image](https://user-images.githubusercontent.com/731333/31043975-f83a4644-a58b-11e7-993c-045948cb7d60.png)
